--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: jenkins
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: jenkins
  template: 
    metadata: 
      labels: 
        app: jenkins
    spec: 
      containers: 
        - 
          command: ["java", "-XX:+HeapDumpOnOutOfMemoryError", "-XX:HeapDumpPath=/tmp/dump-test/snapshot.bin", "-jar", "/usr/share/jenkins/jenkins.war"]
          image: "jenkins/jenkins:lts"
          name: jenkins
		  resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports: 
            - 
              containerPort: 8080
          volumeMounts: 
            - 
              mountPath: /var/jenkins_home
              name: jenkins-home
            - 
              mountPath: /tmp
              name: dump-test
        - 
          command: 
            - /bin/sh
          image: busybox
          name: sidecar-container1
          resources: {}
          tty: true
          volumeMounts: 
            - 
              mountPath: /tmp
              name: dump-test
      volumes: 
        - 
          emptyDir: {}
          name: jenkins-home
        - 
          emptyDir: {}
          name: dump-test
